// 英検3級単語リスト
const wordList = [
    { word: "できる", choices: ["able", "about", "above", "abroad"], answer: "able", example: { en: "Are you able to swim?", ja: "あなたは泳ぐことができますか？" } },
    { word: "～について；およそ", choices: ["about", "above", "abroad", "across"], answer: "about", example: { en: "Let's talk about your plan.", ja: "あなたの計画について話しましょう。" } },
    { word: "～の上に", choices: ["above", "abroad", "across", "action"], answer: "above", example: { en: "The plane is flying above the clouds.", ja: "飛行機が雲の上を飛んでいます。" } },
    { word: "海外へ", choices: ["abroad", "across", "action", "activity"], answer: "abroad", example: { en: "I want to study abroad someday.", ja: "いつか海外に留学したいです。" } },
    { word: "～を横切って", choices: ["across", "action", "activity", "actor"], answer: "across", example: { en: "He swam across the river.", ja: "彼は川を泳いで渡った。" } },
    { word: "行動", choices: ["action", "activity", "actor", "address"], answer: "action", example: { en: "We need to take immediate action.", ja: "私たちはすぐに行動を起こす必要がある。" } },
    { word: "活動", choices: ["activity", "actor", "address", "adult"], answer: "activity", example: { en: "She enjoys outdoor activities.", ja: "彼女は野外活動を楽しんでいる。" } },
    { word: "俳優", choices: ["actor", "address", "adult", "advice"], answer: "actor", example: { en: "He is a famous movie actor.", ja: "彼は有名な映画俳優です。" } },
    { word: "住所", choices: ["address", "adult", "advice", "after"], answer: "address", example: { en: "Please write down your name and address.", ja: "あなたの名前と住所を書いてください。" } },
    { word: "大人", choices: ["adult", "advice", "after", "again"], answer: "adult", example: { en: "This movie is for adults only.", ja: "この映画は大人向けです。" } },
    { word: "助言", choices: ["advice", "after", "again", "age"], answer: "advice", example: { en: "Thank you for your good advice.", ja: "良い助言をありがとうございます。" } },
    { word: "～の後で", choices: ["after", "again", "age", "ago"], answer: "after", example: { en: "Let's meet after school.", ja: "放課後に会いましょう。" } },
    { word: "再び", choices: ["again", "age", "ago", "agree"], answer: "again", example: { en: "Please say that again.", ja: "もう一度それを言ってください。" } },
    { word: "年齢", choices: ["age", "ago", "agree", "air"], answer: "age", example: { en: "What is your age?", ja: "あなたは何歳ですか？" } },
    { word: "～前に", choices: ["ago", "agree", "air", "airport"], answer: "ago", example: { en: "I met him three years ago.", ja: "私は3年前に彼に会いました。" } },
    { word: "同意する", choices: ["agree", "air", "airport", "album"], answer: "agree", example: { en: "I agree with your idea.", ja: "あなたの考えに同意します。" } },
    { word: "空気", choices: ["air", "airport", "album", "all"], answer: "air", example: { en: "The air is clean in the mountains.", ja: "山の空気はきれいです。" } },
    { word: "空港", choices: ["airport", "album", "all", "allow"], answer: "airport", example: { en: "I'll see you off at the airport.", ja: "空港まで見送りに行きます。" } },
    { word: "アルバム", choices: ["album", "all", "allow", "almost"], answer: "album", example: { en: "She showed me her photo album.", ja: "彼女は私に写真のアルバムを見せてくれた。" } },
    { word: "すべての", choices: ["all", "allow", "almost", "alone"], answer: "all", example: { en: "All the students passed the exam.", ja: "全ての生徒が試験に合格した。" } },
    { word: "を許す", choices: ["allow", "almost", "alone", "along"], answer: "allow", example: { en: "My parents don't allow me to stay out late.", ja: "両親は私が遅くまで外出するのを許してくれない。" } },
    { word: "ほとんど", choices: ["almost", "alone", "along", "already"], answer: "almost", example: { en: "It's almost time to go home.", ja: "もうほとんど家に帰る時間だ。" } },
    { word: "一人で", choices: ["alone", "along", "already", "also"], answer: "alone", example: { en: "I like to travel alone.", ja: "私は一人で旅行するのが好きだ。" } },
    { word: "～に沿って", choices: ["along", "already", "also", "always"], answer: "along", example: { en: "Let's walk along the river.", ja: "川に沿って歩きましょう。" } },
    { word: "すでに", choices: ["already", "also", "always", "among"], answer: "already", example: { en: "I have already finished my homework.", ja: "私はもう宿題を終えました。" } },
    { word: "～もまた", choices: ["also", "always", "among", "animal"], answer: "also", example: { en: "She can play the piano and also the guitar.", ja: "彼女はピアノも弾けるし、ギターも弾ける。" } },
    { word: "いつも", choices: ["always", "among", "animal", "another"], answer: "always", example: { en: "He is always kind to everyone.", ja: "彼はいつもみんなに親切だ。" } },
    { word: "～の間で", choices: ["among", "animal", "another", "answer"], answer: "among", example: { en: "He is popular among his classmates.", ja: "彼はクラスメートの間で人気がある。" } },
    { word: "動物", choices: ["animal", "another", "answer", "any"], answer: "animal", example: { en: "What's your favorite animal?", ja: "あなたの好きな動物は何ですか？" } },
    { word: "もう一つの", choices: ["another", "answer", "any", "anything"], answer: "another", example: { en: "Would you like another cup of tea?", ja: "お茶をもう一杯いかがですか？" } },
    { word: "答える；答え", choices: ["answer", "any", "anything", "apartment"], answer: "answer", example: { en: "Please answer the question.", ja: "質問に答えてください。" } },
    { word: "いくつかの；どれでも", choices: ["any", "anything", "apartment", "apple"], answer: "any", example: { en: "Do you have any questions?", ja: "何か質問はありますか？" } },
    { word: "何か；何も（～ない）", choices: ["anything", "apartment", "apple", "arm"], answer: "anything", example: { en: "I didn't eat anything this morning.", ja: "今朝は何も食べなかった。" } },
    { word: "アパート", choices: ["apartment", "apple", "arm", "around"], answer: "apartment", example: { en: "She lives in a small apartment.", ja: "彼女は小さなアパートに住んでいる。" } },
    { word: "リンゴ", choices: ["apple", "arm", "around", "arrive"], answer: "apple", example: { en: "An apple a day keeps the doctor away.", ja: "一日一個のリンゴは医者を遠ざける。" } },
    { word: "腕", choices: ["arm", "around", "arrive", "art"], answer: "arm", example: { en: "He broke his arm playing soccer.", ja: "彼はサッカーをしていて腕を骨折した。" } },
    { word: "～の周りに", choices: ["around", "arrive", "art", "artist"], answer: "around", example: { en: "They sat around the table.", ja: "彼らはテーブルの周りに座った。" } },
    { word: "到着する", choices: ["arrive", "art", "artist", "ask"], answer: "arrive", example: { en: "The train will arrive at 10 a.m.", ja: "電車は午前10時に到着します。" } },
    { word: "芸術", choices: ["art", "artist", "ask", "at"], answer: "art", example: { en: "She is interested in modern art.", ja: "彼女は現代美術に興味がある。" } },
    { word: "芸術家", choices: ["artist", "ask", "at", "aunt"], answer: "artist", example: { en: "He wants to be an artist.", ja: "彼は芸術家になりたいと思っている。" } },
    { word: "尋ねる", choices: ["ask", "at", "aunt", "autumn"], answer: "ask", example: { en: "Don't be afraid to ask for help.", ja: "助けを求めることを恐れないで。" } },
    { word: "～で；～に", choices: ["at", "aunt", "autumn", "away"], answer: "at", example: { en: "I'll meet you at the station.", ja: "駅で会いましょう。" } },
    { word: "おば", choices: ["aunt", "autumn", "away", "baby"], answer: "aunt", example: { en: "My aunt lives in Kyoto.", ja: "私のおばは京都に住んでいます。" } },
    { word: "秋", choices: ["autumn", "away", "baby", "back"], answer: "autumn", example: { en: "Autumn is my favorite season.", ja: "秋は私の一番好きな季節です。" } },
    { word: "離れて", choices: ["away", "baby", "back", "bad"], answer: "away", example: { en: "He walked away without saying goodbye.", ja: "彼はさよならも言わずに歩き去った。" } },
    { word: "赤ちゃん", choices: ["baby", "back", "bad", "bag"], answer: "baby", example: { en: "The baby is sleeping.", ja: "赤ちゃんは眠っています。" } },
    { word: "背中；後ろへ", choices: ["back", "bad", "bag", "ball"], answer: "back", example: { en: "I'll be back in an hour.", ja: "1時間で戻ります。" } },
    { word: "悪い", choices: ["bad", "bag", "ball", "banana"], answer: "bad", example: { en: "I have a bad headache.", ja: "ひどい頭痛がします。" } },
    { word: "かばん", choices: ["bag", "ball", "banana", "band"], answer: "bag", example: { en: "What's in your bag?", ja: "あなたのかばんの中には何が入っていますか？" } },
    { word: "ボール", choices: ["ball", "banana", "band", "bank"], answer: "ball", example: { en: "Let's play with a ball.", ja: "ボールで遊びましょう。" } },
    { word: "美しい", choices: ["beautiful", "because", "become", "bed"], answer: "beautiful", example: { en: "What a beautiful flower!", ja: "なんて美しい花でしょう！" } },
    { word: "なぜなら", choices: ["because", "become", "bed", "bedroom"], answer: "because", example: { en: "I was late because the train was delayed.", ja: "電車が遅れたので、私は遅刻しました。" } }
];
